apiVersion: v1 
kind: Pod  
metadata: 
 name: nginx 
spec:
 containers: 
 - name: bear 
   image: upergiantkir/animals:bear
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   volumeMounts:
    - name: app-storage
      mountPath: /storage
   ports: 
   - containerPort: 8080
   volumeMounts:
    - name: app-storage
      mountPath: /storage
 volumes:
  - name: app-storage
    emptyDir: {}

